const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const count = await prisma.contact.count();
  console.log('Current contacts in DB:', count);
  
  const newContact = await prisma.contact.create({
    data: {
      name: 'Test Administrator',
      email: 'admin@example.com',
      subject: 'Dashboard Connection Test',
      message: 'This is a test message generated by the system to verify the Admin Dashboard is successfully pulling data from the database. If you can see this, the connection is perfect!',
    }
  });
  
  console.log('Successfully created test contact:', newContact.id);
}

main()
  .catch(e => console.error(e))
  .finally(() => prisma.$disconnect());
